# vim:ft=ansible
---
- hosts: localhost

  tasks:

    - name: install deps
      apk:
        name={{ item }}
        state=present
        update_cache=yes
      with_items:
        - ack
        - ansible
        - ca-certificates
        - coreutils
        - curl
        #- g++
        - gcc
        - git
        - grep
        - imagemagick
        - lftp
        - make
        - musl-dev
        - nodejs
        - python3
        - python3-dev
        - wget
      become: yes

    - name: pip status
      stat:
        path=/usr/bin/pip
      register: pip

    - name: install pip
      shell: curl https://bootstrap.pypa.io/get-pip.py | python3
      become: yes
      when: pip.stat.exists == False

    - name: install pip packages
      pip:
        name={{ item }}
        executable=pip3
      with_items:
        - beautifulsoup4
        - cookiecutter==1.4.0
        - flickr2markdown
        - ipython[notebook]==2.4.1
        - jinja2-slug
        - markdown
        - pelican==3.7
        - tzlocal
        - virtualenv
      become: yes

    - name: add flickr2markdown config
      copy:
        src=flickr2markdown
        dest=~/.flickr2markdown

    - name: install js packages
      npm:
        name={{ item }}
        path=/vagrant
        state=present
        global=yes
      with_items:
        - bower
        - gulp
        - gulp-rename
        - gulp-less
        - gulp-minify-css
      become: yes

    - name: set timezone
      copy:
        content="Europe/Berlin"
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
      become: yes

    - name: clone batcave
      git:
        repo=https://github.com/xsteadfastx/batcave.git
        dest=~/.batcave
        force=yes

    - name: run batcave
      command:
        ansible-playbook -i hosts shell.yml -c local --extra-vars="hosts=127.0.0.1"
        chdir=~/.batcave
      environment:
        SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

    - name: export variables
      lineinfile:
        dest=~/.zshrc
        line='{{ item }}'
      with_items:
        - export PYTHONIOENCODING=UTF-8
        - export LC_ALL=C.UTF-8
        - export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

    - name: no git colors
      command: git config --global color.ui false
