# vim:ft=ansible
---
- hosts: 127.0.0.1
  connection: local

  tasks:

    - name: install deps
      apk:
        state: present
        update_cache: true
        name:
          - ack
          - ansible
          - bash-completion
          - ca-certificates
          - coreutils
          - curl
          - cython
          - gcc
          - git
          - grep
          - imagemagick
          - lftp
          - linux-headers
          - make
          - musl-dev
          - nodejs
          - python3
          - python3-dev
          - wget
      become: yes

    - name: pip status
      stat:
        path=/usr/bin/pip
      register: pip

    - name: install pip
      shell: curl https://bootstrap.pypa.io/get-pip.py | python3
      become: yes
      when: pip.stat.exists == False

    - name: install pip packages
      pip:
        executable: pip3
        name:
          - beautifulsoup4
          - cookiecutter==1.4.0
          - flickr2markdown
          - ipython>=4.0
          - jinja2-slug
          - jupyter>=1.0
          - markdown
          - nbconvert>=4.0
          - pelican==4.0.1
          - typogrify
          - tzlocal
          - virtualenv
      become: yes

    - name: add flickr2markdown config
      copy:
        src=flickr2markdown
        dest=~/.flickr2markdown

    - name: set timezone
      copy:
        content="Europe/Berlin"
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
      become: yes
