# vim:ft=ansible
---
- hosts: localhost

  tasks:

    - name: install deps
      apk:
        name={{ item }}
        state=present
        update_cache=yes
      with_items:
        #- g++
        - ack
        - ansible
        - ca-certificates
        - coreutils
        - curl
        - gcc
        - git
        - grep
        - imagemagick
        - lftp
        - make
        - musl-dev
        - nodejs
        - python3
        - python3-dev
        - wget
      become: yes

    - name: pip status
      stat:
        path=/usr/bin/pip
      register: pip

    - name: install pip
      shell: curl https://bootstrap.pypa.io/get-pip.py | python3
      become: yes
      when: pip.stat.exists == False

    - name: install pip packages
      pip:
        name={{ item }}
        executable=pip3
      with_items:
        - beautifulsoup4
        - cookiecutter==1.4.0
        - flickr2markdown
        - ipython[notebook]==2.4.1
        - jinja2-slug
        - markdown
        - pelican==3.7.1
        - typogrify
        - tzlocal
        - virtualenv
      become: yes

    - name: add flickr2markdown config
      copy:
        src=flickr2markdown
        dest=~/.flickr2markdown

    - name: set timezone
      copy:
        content="Europe/Berlin"
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
      become: yes

    - name: export variables
      lineinfile:
        dest=~/.config/fish/config.fish
        line='{{ item }}'
      with_items:
        - set -gx PYTHONIOENCODING UTF-8
        - set -gx SSL_CERT_FILE /etc/ssl/certs/ca-certificates.crt

    - name: no git colors
      command: git config --global color.ui false
