---
kind: pipeline
name: default
steps:
  - name: build and upload
    image: golang:1.14.0-alpine3.11
    pull: always
    environment:
      RCLONE_CONF:
        from_secret: rclone.conf
    commands:
      - apk add --no-cache make rclone
      - mkdir -p ~/.config/rclone
      - echo $RCLONE_CONF > ~/.config/rclone/rclone.conf
      - cat ~/.config/rclone/rclone.conf
      - make install_deps
      - make build
      - make ftp_upload
    when:
      branch:
        - master
