kind: pipeline
name: default

workspace:
  base: /blog

steps:

  - name: submodules
    image: docker:git
    commands:
      - git submodule init
      - git submodule update --recursive --remote

  - name: build and upload
    image: xsteadfastx/blog
    pull: always
    environment:
      FTP_PASS:
        from_secret: ftp_pass
    commands:
      - sudo chown -R blog:blog /blog
      - make ftp_upload
