---
kind: pipeline
name: default
concurrency:
  limit: 1
steps:
  - name: build and upload
    image: golang:1.14.0-alpine3.11
    pull: always
    environment:
      FTP_PASS:
        from_secret: ftp_pass
      WEBMENTIONIO_TOKEN:
        from_secret: webmentionio_token
    commands:
      - apk add --no-cache curl make git npm jq
      - mkdir -p ~/.config/rclone
      - make rclone_config
      - cat ~/.config/rclone/rclone.conf
      - make install_deps
      - curl "https://webmention.io/api/mentions?token=$$WEBMENTIONIO_TOKEN" -o data/mentions.json
      - cat data/mentions.json|jq
      - make build
      - make ftp_upload
      - npm install @remy/webmention
      - npx webmention https://xsteadfastx.org/index.xml --limit 10 --send
    when:
      branch:
        - master
