---
kind: pipeline
name: default
concurrency:
  limit: 1
steps:
  - name: build
    image: xsteadfastx/blog
    pull: always
    environment:
      WEBMENTIONIO_TOKEN:
        from_secret: webmentionio_token
    commands:
      - curl "https://webmention.io/api/mentions?token=$$WEBMENTIONIO_TOKEN" -o data/mentions.json
      - make build
    when:
      branch:
        - master

  - name: upload
    image: xsteadfastx/blog
    pull: always
    environment:
      FTP_PASS:
        from_secret: ftp_pass
    commands:
      - make rclone_config
      - make ftp_upload
    when:
      branch:
        - master

  - name: mention
    image: xsteadfastx/blog
    pull: always
    commands:
      - npx webmention https://xsteadfastx.org/ --limit 10 --send --debug
    when:
      branch:
        - master
