---
kind: pipeline
name: default
steps:
  - name: build and upload
    image: golang:1.14.0-alpine3.11
    pull: always
    environment:
      FTP_PASS:
        from_secret: ftp_pass
    commands:
      - apk add --no-cache make
      - mkdir -p ~/.config/rclone
      - make rclone_config
      - cat ~/.config/rclone/rclone.conf
      - make install_deps
      - make build
      - make ftp_upload
    when:
      branch:
        - master
