---
- hosts: all

  tasks:

    - name: install deps
      apt:
        name={{ item }}
        state=present
      with_items:
        - git
        - ansible
        - python3
        - python3-dev
        - python3-pip
        - python-virtualenv
        - libxml2-dev
        - libxslt1-dev
        - zlib1g-dev
        - lftp
        - pandoc
        - nodejs
        - nodejs-legacy
        - npm
        - mc
      sudo: yes

    - name: clone batcave
      git:
        repo=https://github.com/xsteadfastx/batcave.git
        dest=~/batcave

    - name: run batcave
      command:
        ansible-playbook -i hosts site.yml --skip-tags "x11" -c local
        chdir=~/batcave

    - name: install blogging packages
      pip:
        name={{ item }}
        executable=pip3
      with_items:
        - pelican==3.6.3
        - markdown
        - ipython[notebook]==2.4.1
        - beautifulsoup4
        - cookiecutter
      sudo: yes

    - name: clone pelican-plugins
      git:
        repo=https://github.com/getpelican/pelican-plugins.git
        dest=/vagrant/pelican-plugins
        accept_hostkey=yes

    - name: clone flickr2markdown
      git:
        repo=https://github.com/xsteadfastx/flickr2markdown.git
        dest=/opt/flickr2markdown
      sudo: yes

    - name: install flickr2markdown deps
      pip:
        requirements=/opt/flickr2markdown/requirements.txt
        virtualenv=/opt/flickr2markdown/env
        virtualenv_command="virtualenv -p /usr/bin/python3"
      sudo: yes

    - name: copy flickr2markdown shellscript
      copy:
        src=files/flickr2markdown
        dest=/usr/local/bin/flickr2markdown
        mode=755
      sudo: yes

    - name: export variables
      lineinfile:
        dest=~/.zshrc
        line="{{ item }}"
      with_items:
        - export PYTHONIOENCODING=UTF-8
        - export LC_ALL=C.UTF-8

    - name: install bower
      npm:
        name=bower
        global=yes
        state=present
      sudo: yes
